runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /about
  static_files: www/about/about.html
  upload: www/about/about.html

- url: /gallery
  static_files: www/gallery/gallery.html
  upload: www/gallery/gallery.html

- url: /about/about.html
  static_files: www/about/about.html
  upload: www/about/about.html

- url: /gallery/gallery.html
  static_files: www/gallery/gallery.html
  upload: www/gallery/gallery.html

- url: /about.html
  static_files: www/about.html
  upload: www/about.html

- url: /gallery.html
  static_files: www/gallery.html
  upload: www/gallery.html
  
- url: /(.*)
  static_files: www/\1
  upload: www/(.*)